---
- hosts: all
  tasks:

  - name: Download script HSP.ps1
    win_get_url:
      url: https://cloud.t4b.com/f/90d99b0b4c384ea5934b/?dl=1
      dest: C:\
  
  #- name: Execute script
    #win_shell: C:\HSP.ps1


  - name: Remove HSP.ps1 file
    win_file:
      path: C:\HSP.ps1
      state: absent