---

- hosts: all

  tasks:
  - name: check user Tteam is available
    win_user:
      name: Tteam
      state: query
#  - name: Create local user
#    win_user:
#      name: Tteam
#      password: 'kj79HK802Nmml~#4k90mfjde'
#      groups: Administrators
#      update_password: always
#      password_never_expires: yes
#      state: present

                                    
