---

- hosts: all
  tasks:
  - name: Get Hang Process
    win_shell: Get-Process | where-object {$_.Responding -eq $false}
    #win_shell: ls
    register: result

  - debug:
      var: result.stdout_lines
  
